### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/DSCI_532_L02_group206_ms1#19]
Great work! Keep it up!

You distribute your work really well and have the right amount of detail in your commit messages.
For team work planning and communication try to use issues or alternatively check out Github's project functionality.

**Comment by slumnitz** [comment]
Here are a couple of things you could improve on in future:

* Research Questions you want to answer are not clear. You describe what could be explored with your dashboard, though you are not stating your research objectives clearly. I'd suggest to use your current text as a general intro to the paragraph and then clearly stating 2-3 Questions you are going to answer in bullet points.
* Team work contract could be more specific: What are tasks? Who takes which jobs? When are they due?

Again overall really well done!

**Comment by kfoofw** [comment]
Feedback addressed with recent commits! :)
