### ISSUE TITLE
Feedback Session

### ISSUE THREAD

**Issue by cgostic** [UBC-MDS/DSCI_532_L02_group206_ms1#29]
Feedback:

* Maybe include some info on the shelter? 
* Consistent spelling of out-takes... define out-takes/outcomes!
* Include indication that year range applies to all graphs. Possibly change location?
* Include indication that month/animal applies to both bar charts
* Small change: consistent capitalization of graph titles
* Space between radio button and text
* Consider integer y-axes, static y-axes for bar charts
* Round tool tips for time spent in shelter
* Format titles for tooltips
* Link to github
* Tooltip on line chart

**Comment by Keanna-K** [comment]
Created a common issue with all feedback suggestions from our lab session #32
