### ISSUE TITLE
Feedback on Dashboard

### ISSUE THREAD

**Issue by aakanksha023** [UBC-MDS/DSCI_532_L02_group206_ms1#31]
- Line plot is not very informative. It would be interesting to know the trends in adoption highlighting seasons with festivals. For ex. around Thanksgiving and Christmas do the adoption rates increase? If yes for which animal(s)?
- Tool tip missing, so numbers are not readable on the line charts
- Legend seems out of place and not aesthetically pleasing
- X axis seems incorrect. 'Dec' from previous year is included
- The two Histograms in the middle were not intuitive as 
- The last box-plot was very informative and answered an interesting and relevant research question on its own. This plot could be the landing plot
- Overall HTML layout could be improved. For ex. drop downs are oddly placed, extra white space etc.
- Titles and Axes are either too tiny to read, or too cluttered. For ex Week days could be abbreviated, Titles should not contain info which is there on the axes already etc.

**Comment by Keanna-K** [comment]
Created a common issue with all feedback suggestions from our lab session #32
