### ISSUE TITLE
Refactor options in filters in app.py

### ISSUE THREAD

**Issue by kfoofw** [UBC-MDS/DSCI_532_L02_group206_ms1#39]
Monthly filter for plots 2 and 3: @amank90 
Intake Health condition filter for Plot 5: @kfoofw

**Comment by kfoofw** [comment]
For plot 5 filter on intake health condition, I decided not to refactor the code as I need them in a certain order for app display. It will be pointless to specify the list out in an ordered manner again before unwrapping them again in a list comprehension. 

Thus, I will leave it as it is since it does not comprise of too many options (about 10), and actually to me, it is more readable in terms of what options I put in for the drop list.

**Comment by kfoofw** [comment]
Remaining portion on "Monthly filter Plot 2" for @amank90 to comment on before issue is completed.

**Comment by amank90** [comment]
Issue resolved.
[Link to commit](https://github.com/UBC-MDS/DSCI_532_L02_group206_ms1/tree/7aec086cffb0a012942f5fe195e57a0477fc450e)
